[env:esp32c3-sm-motor-l298]
platform  = espressif32
framework = arduino
board     = esp32-c3-devkitm-1
upload_speed  = 115200
monitor_speed = 115200
board_build.filesystem = littlefs
build_src_filter = +<motor_l298/*>
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
  mathieucarbou/ESPAsyncWebServer @ ^3.3.23
  mathieucarbou/AsyncTCP @ ^3.3.2
